version: "1.0"
services:
    jupyter-lab:
      build: .
      ports:
        - "8888:8888"
#      volumes:
#        - C:\Users\Taylor\PycharmProjects\tf_object_detection\tf:/tf
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]